version: "3.9"

services:
  edge-nginx:
    image: nginx:1.27
    container_name: edge-nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
    networks:
      - edge_proxy
    restart: unless-stopped

networks:
  edge_proxy:
    external: true
